language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make
  - make test
  - make gcov
branches:
  only:
    - master
after_success:
  - codecov -t d73be3bb-e5e5-420d-beb2-91b31c919b1d -X gcov
